name: Create Release
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Requirements
        run: |
          npm install -g typescript
          npm install -g webpack
          npm install -g @vercel/ncc
      - name: Build the release
        run: |
          npm run release
      - name: Push release to release branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create Release
          branch: releases
          tagging_message: 'ci'
          push_options: '--force'
          create_branch: true
          status_options: '--untracked-files=all'
          add_options: '-u'
          file_pattern: 'dist/*'
      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          if-no-files-found: error
