name: Test Installing LinuxDeploy on default options

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: "npm install"
        run: npm install
      - name: "npm run build"
        run: npm run build
      - name: Install LinuxDeploy
        uses: ./
      - name: Launch LinuxDeploy
        run: |
          linuxdeploy-x86_64.AppImage --version
        shell: bash
